### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by matthewblott** [loomchild/theo-rails#3]
I fired up a new Rails project and added the gem and perhaps naively expected things to work but that's not the case. I can't see any instructions for how to configure things?

Also, not too important but I assume the backtick at the end of the following snippet on the homepage isn't supposed to be there?
```html
<_button size="large" />`
```

**Comment by loomchild** [comment]
The things should work out of the box after adding a gem. Are you sure that you created a view with `.html.theo` extension?

You are right that documentation is lacking - I promise to improve it over time after the library stabilizes. For now, I have added a simple "Getting started" section to README.

You are right about the extra backtick - fixed.

**Comment by matthewblott** [comment]
Anything with a `.theo` extension causes a crash.

**Comment by loomchild** [comment]
Weird, sorry for that. Could you share what is the error message?

I updated the README again, installation should actually be done with `bundle add theo-rails` instead of `gem install theo-rails`. 

I just tested it on vanilla Rails 7.2 project and it worked. I installed theo, then added a controller and route, and was able to display `.theo` partial.

**Comment by matthewblott** [comment]
Okay, it's working. I misunderstood how to apply the file suffix! You can close, sorry for the confusion :-)
