### ISSUE TITLE
Change Underscore

### ISSUE THREAD

**Issue by matthewblott** [loomchild/theo-rails#4]
Is an underscore the best convention to use for components? One reason I dislike ERB is because it doesn't play nicely with HTML design. I like to use tags that function like HTML elements when viewed in the browser without going through a server engine.

The problem with Theo's current syntax is this doesn't work very well and you can see the tag written as text on the web page.

Basically this:
```html
<_footer />
```

Becomes this:

![Screenshot 2024-10-01 at 16 28 21](https://github.com/user-attachments/assets/a36b903a-8bd0-4555-a6ed-45020cffb52a)

Whereas this:
```html
<theo:footer />
```

Is rendered gracefully (it is part of the HTMl of the image above).

Just my thoughts, it's your library so feel free to ignore :-)

**Comment by loomchild** [comment]
Hi @matthewblott,

Thanks for your tickets, I will do my best to look into them over the weekend.

The syntax is still getting developed and changed (see https://github.com/loomchild/theo-rails/issues/2), so your insight is valuable.

Could you please share where do you see this strange rendering? I quickly tried to open a simple file containing only `<_footer />` and it displayed normally in FF and Chrome. Feel free to also send the entire file that doesn't render correctly.

I don't really like the prefix because it's longer to read when reviewing the code, but if underscore is causing issues, then perhaps it could be optional (e.g. anything that isn't a standard HTML tag will be treated as partial) or a suffix as original.

**Comment by matthewblott** [comment]
This is a vanilla HTML file:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
  </head>
  <body>
    <a href%="root_path">Home</a>
    <_footer />
    <theo:footer />
  </body>
</html>
```
This is how it appears in Chrome based browsers:

![Screenshot 2024-10-03 at 12 00 32](https://github.com/user-attachments/assets/b21d1a67-fad3-4d17-b97c-05bb74bef433)

**Comment by loomchild** [comment]
Ah, I see what you mean, you don't want the tag to be visible. Thanks for clarification.

Agree it makes sense, since if the tag contains some content e.g. `<theo:footer>FOOTER</theo:footer>`, the unknown tag will be ignored and content will still be shown.

**Comment by loomchild** [comment]
Since it's a fundamental question, I opened a new ticket describing potential soltions: #5. Let's continue the discussion there.
